BLOG/Article/urls.py
from django.urls import path,re_path
from .import views
app_name='article'
urlpatterns = [    
    path('',views.indexx,name="home"),
     path('create',views.create,name="create_post"),
     path('<slug:me>',views.article_details,name='details'),

]

BLOG/accounts/urls.py
from django.urls import path,re_path
from .import views
app_name='accounts'
urlpatterns = [    
    path('signup',views.signup_view,name="signup"), 
    path('login',views.login_view,name="login"),
     path('logout',views.logout_view,name="logout"),  


]

BLOG/me/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from Article import views as home
urlpatterns = [
    path('admin/',admin.site.urls),
    path('about',views.about),
    path('',home.indexx,name="home"),
    path('Article/',include('Article.urls')),
    path('accounts/',include('accounts.urls'))

]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

BLOG/Article/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Article(models.Model):
    title=models.CharField(max_length=100)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(default='hhh.jpg',blank=True)
    uthor=models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50]+"..."

BLOG/accounts/models.py
from django.db import models

# Create your models here.

BLOG/Article/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model=models.Article
        fields=['title','slug','body','thumb']

BLOG/Article/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms
# Create your views here.
def indexx(request):
    articles =Article.objects.all().order_by('date')
    return render(request,'articles/index.html',{'article': articles})
def article_details(request,me):
    artivle1=Article.objects.get(slug = me)
    return render(request,'articles/detailed.html',{'article_val': artivle1})

@login_required(login_url="/accounts/login")
def create(request):
    if request.method=='POST':
         formm=forms.CreateArticle(request.POST,request.FILES)
         if formm.is_valid():
            instance=formm.save(commit=False)
            instance.uthor=request.user
            instance.save()
            return redirect('accounts:login')
            
    else:
       formm=forms.CreateArticle()
    return render(request,'articles/create.html',{"form":formm})

BLOG/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.
def signup_view(request):
    if request.method=='POST':
          form= UserCreationForm(request.POST)
          if(form.is_valid()):
              form.save()
              return redirect('accounts:login')
    else:      
        form= UserCreationForm()
    return render(request,'account/signup.html',{'form':form})
def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if(form.is_valid()):
            #login
            user=form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
              return redirect('article:home')
    else:
        form=AuthenticationForm()
    return render(request,'account/login.html',{'form':form})
def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('accounts:login')
        

BLOG/me/views.py
from django.http import HttpResponse
from django.shortcuts import render
def home(request):
    return HttpResponse('HOME PAGE')
def about(request):
    return render(request,'home.html')

BLOG/Article/templates/articles/create.html
{% extends 'base_file.html' %}

{%block content%}
<div class="container" style="width:35%;margin-top: 2em;">
    <!-- Content here -->
    <div class="card p-2" style="width: 30rem;">
      <div class="card-body">
        <h5 class="card-title">POST AN ARTICLE</h5>        
        <p class="card-text">
          <form action="{% url 'article:create_post' %}" method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form}}<br><br>
            <input type="submit" value="Submit">
          </form>
        </p>     
      </div>
    </div>
 

</div>
{%endblock%}

BLOG/Article/templates/articles/detailed.html
{%extends 'base_file.html'%}
{%block content%}
<div class="container" style="margin-top: 1em;">
<div class="articlcle">
    <div class="card">
        <div class="card-header">
            {{article_val.title}}
        </div>
        <div class="card-body bg-secondary text-white">
          <h5 class="card-title"><img class="img-responsive rounded-circle" src="{{article_val.thumb.url}}" alt="" width="10%"></h5>
          <p class="card-text">{{article_val.body}}</p>
          <p class="card-text">Date Posted:{{article_val.date}}</p>          
        </div>
      </div>    
</div>
</div>
{%endblock%}

BLOG/Article/templates/articles/index.html
{%extends 'base_file.html'%}
   {%block content%} 
   <div class="container">
    <div class="article">
        <!-- template tag -->
        {%for article in  article%}
        <div class="card" style="margin-top: 1em;">
            <div class="card-body">
              <h5 class="card-title">{{article.title}}</h5>
              <p class="card-text">{{article.snippet}}}</p>
              <p class="card-text">{{article.date}}}</p>
              <a href="{% url 'article:details' me=article.slug %}" class="btn btn-primary">More</a>
            </div>
          </div>              
        {%endfor%}
    </div>
</div>
{%endblock %}

BLOG/templates/base_file.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'deno.css' %}">
    <script src="{% static 'jvs.js' %}"></script>    
</head>
<body>
    <div class="wrapper">        
        {% if user.is_authenticated%}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <a class="navbar-brand" href="{% url 'home'%}">Home</a>
              <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled"></a>
                  </li>
                </ul>
                <div class="d-flex">                    
                    <form action="{% url 'accounts:logout'%}" method="post"class="p-3">
                        {%csrf_token%}
                        <button type="submit" style="border: none; outline: none; font-size: 1.5em;">logout</button>
                    </form>                        
                    <a class="navbar-brand p-3"style="border: none; outline: none; font-size: 1.5em;" href="{% url 'article:create_post'%}">add</a>
                </div>
              </div>
            </div>
        </nav>
        {%else%}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <a class="navbar-brand" href="{% url 'home'%}">Home</a>
              <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#"></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled"></a>
                  </li>
                </ul>
                <div class="d-flex">                    
                    <form action="{% url 'accounts:logout'%}" method="post" class="p-3">
                        {%csrf_token%}
                        <button type="submit" style="border: none; outline: none; font-size: 1.5em;">Login</button>
                    </form>                        
                    <a class="navbar-brand p-3" style="border: none; outline: none; font-size: 1.5em;" href="{% url 'accounts:signup'%}">Sign UP</a>
                </div>
              </div>
            </div>
        </nav>
      
    {%endif%}
        {%block content%}

        {%endblock%}  
    </div>

</body>
</html>

BLOG/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Hello</h2>
</body>
</html>